server:
  port: 8066

spring:
  application:
    name: department-service


eureka:
  client:
    registerWitheEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
